### ISSUE TITLE
assertj-swing 3.9.2 not compatible with assertj-core 3.17.1

### ISSUE THREAD

**Issue by henri-tremblay** [assertj/assertj-swing#252]
Doing
```
val newFrame = WindowFinder.findFrame("EditConfigFrame").using(robot)
newFrame.requireVisible()
```

I get `java.lang.NoSuchMethodError: org.assertj.core.api.AbstractBooleanAssert.as(Lorg/assertj/core/description/Description;)Lorg/assertj/core/api/AbstractAssert;`

**Comment by joel-costigliola** [comment]
hey Henri, 
this is hopefully fixed by https://github.com/joel-costigliola/assertj-swing/pull/251 and was initially raised in https://github.com/joel-costigliola/assertj-core/issues/1974.

I'm not the active maintainer on that project, I have tried releasing it but failed miserably 👍 
@croesch can you release a version if you find a bit of time or let me know how to release it.

**Comment by croesch** [comment]
Thanks for reporting @henri-tremblay  and fixing @joel-costigliola - as promised I'll do the release this week.

**Comment by scordio** [comment]
Hi @henri-tremblay and @tifhorn, `assertj-swing` 3.17.0 has been released (thanks @croesch!) and it should hopefully fix the issue you met.

**Comment by croesch** [comment]
You're welcome. AssertJ-Swing 3.17.0 depends on AssertJ core 3.17.0. This is because we'd like to do a release again the next days.

But anyway, they should be compatible - reopen, if not :-)
